---
- name: Generate stream.conf file
  template:
    src: stream.conf.j2
    dest: /opt/netdata/etc/netdata/stream.conf
    owner: netdata
    mode: 0640
  notify: restart netdata
- name: Copying netdata.conf file to the host
  copy:
    src: netdata.conf
    dest: /opt/netdata/etc/netdata/netdata.conf
    owner: netdata
    group: netdata
    mode: '0644'
